# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spt < Formula
  desc "CLI for managing Coder workspaces on Azure"
  homepage "https://github.com/SmartPointsTech/spt-flow"
  version "0.9.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://sptflowreleases.blob.core.windows.net/cli/v0.9.0/spt_0.9.0_darwin_amd64.tar.gz"
      sha256 "b4bfd4536ff39226d425f9b4c4a172c0b29eba40de4e3ff74183b85e78f7ac3f"

      define_method(:install) do
        bin.install "spt"
      end
    end
    if Hardware::CPU.arm?
      url "https://sptflowreleases.blob.core.windows.net/cli/v0.9.0/spt_0.9.0_darwin_arm64.tar.gz"
      sha256 "49e81790b8dfab9dd69a30538395dbbb3b61aaee1059ccec27afeeff5c2eca1b"

      define_method(:install) do
        bin.install "spt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://sptflowreleases.blob.core.windows.net/cli/v0.9.0/spt_0.9.0_linux_amd64.tar.gz"
      sha256 "9f6cdfc3e98ce595ffea27d765893510e52b5007a32b01491586005962af6479"
      define_method(:install) do
        bin.install "spt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://sptflowreleases.blob.core.windows.net/cli/v0.9.0/spt_0.9.0_linux_arm64.tar.gz"
      sha256 "cc451d3411bde8323cfc7f3c24c0d721db6a5b2f59e63a74d89578e07020e381"
      define_method(:install) do
        bin.install "spt"
      end
    end
  end

  test do
    system "#{bin}/spt", "version"
  end
end
